# Numpy


#### 1. Import the numpy package under the name `np` (★☆☆)

(**hint**: import … as …)


In [50]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

(**hint**: np.\_\_version\_\_, np.show_config)


In [51]:
print(np.__version__)
np.show_config()


1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

(**hint**: np.zeros)


In [52]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

(**hint**: size, itemsize)


In [53]:
vec = np.zeros(10)
vec.size * vec.itemsize


80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

(**hint**: np.info)


In [54]:
np.info('add')


     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

(**hint**: array\[4\])


In [55]:
vec = np.array([None]*10)
vec[4] = 1
vec


array([None, None, None, None, 1, None, None, None, None, None],
      dtype=object)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

(**hint**: np.arange)


In [56]:
np.arange(10, 50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

(**hint**: array\[::-1\])


In [57]:
np.arange(0, 10)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

(**hint**: reshape)


In [58]:
np.arange(0, 9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

(**hint**: np.nonzero)


In [59]:
np.array([1, 2, 0, 0, 4, 0]).nonzero()


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

(**hint**: np.eye)


In [60]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

(**hint**: np.random.random)


In [61]:
np.random.random((3, 3, 3))


array([[[0.15436605, 0.96529066, 0.09470408],
        [0.41803002, 0.96108111, 0.60442148],
        [0.6707595 , 0.06991776, 0.23283491]],

       [[0.21446645, 0.44395939, 0.93735056],
        [0.92603809, 0.4667552 , 0.36341628],
        [0.45417155, 0.74030733, 0.31357846]],

       [[0.6160079 , 0.0024999 , 0.83665235],
        [0.6388281 , 0.9682015 , 0.07678292],
        [0.71231092, 0.34848184, 0.25562099]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

(**hint**: min, max)


In [62]:
vec = np.random.random((10, 10))
vec.min(), vec.max()


(0.0013042245068266567, 0.9958955960602534)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

(**hint**: mean)


In [63]:
np.random.random(30).mean()


0.6090295988391279

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

(**hint**: array\[1:-1, 1:-1\])


In [64]:
vec = np.ones((5, 5), dtype=np.int8)
vec[1:-1, 1:-1] = 0
vec


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

(**hint**: np.pad)


In [65]:
vec = np.ones((3, 3), dtype=np.int8)
np.pad(vec, pad_width=1)


array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

#### 17. What is the result of the following expression? (★☆☆)

(**hint**: NaN = not a number, inf = infinity)


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```


In [66]:
np.isnan(0 * np.nan),\
    (np.nan == np.nan) == False,\
    (np.inf > np.nan) == False,\
    np.isnan(np.nan - np.nan),\
    (0.3 == 3 * 0.1) == False


(True, True, True, True, True)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

(**hint**: np.diag)


In [67]:
np.diag([1, 2, 3, 4], -1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

(**hint**: array\[::2\])


In [68]:
vec = np.ones((8, 8), dtype=np.int8)
vec[1::2, ::2] = 0
vec[::2, 1::2] = 0
vec


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

(**hint**: np.unravel_index)


In [69]:
np.unravel_index(100, (6, 7, 8))


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

(**hint**: np.tile)


In [70]:
np.tile([[0, 1], [1, 0]], (4, 4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

(**hint**: (x - min) / (max - min))


In [71]:
vec = np.random.randint(1, 10, (5, 5))
(vec-vec.min())/(vec.max()-vec.min())


array([[0.75 , 0.25 , 0.25 , 1.   , 0.875],
       [0.125, 1.   , 0.5  , 0.875, 0.5  ],
       [0.625, 0.875, 0.   , 0.125, 0.25 ],
       [0.5  , 0.25 , 1.   , 0.625, 0.5  ],
       [1.   , 0.875, 0.75 , 1.   , 0.375]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

(**hint**: np.dtype)


In [72]:
RGBA = np.dtype([('Vals', np.ubyte, 4)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

(**hint**: np.dot | @)


In [73]:
a = np.random.randint(1, 10, (5, 3))
b = np.random.randint(1, 10, (3, 2))
np.dot(a, b)


array([[ 57,  96],
       [ 27, 114],
       [ 25,  86],
       [ 50, 109],
       [ 44, 133]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

(**hint**: >, <=)


In [74]:
vec = np.arange(10)
np.where((vec > 3) & (vec <= 8), vec*-1, vec)


array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)

(**hint**: np.sum)


```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```


In [75]:
9, 10


(9, 10)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [76]:
print('Z**Z, 2 << Z >> 2, Z <- Z, 1j*Z, Z/1/1 are legal')


Z**Z, 2 << Z >> 2, Z <- Z, 1j*Z, Z/1/1 are legal


#### 28. What are the result of the following expressions?


```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [77]:
print('nan, 0, array([-9.22337204e+18])')


nan, 0, array([-9.22337204e+18])


#### 29. How to round away from zero a float array ? (★☆☆)

(**hint**: np.uniform, np.copysign, np.ceil, np.abs)


In [78]:
x = np.random.randn(1, 4)
y = np.copysign(np.ceil(np.abs(x)), x)
x, y


(array([[-0.33700611, -0.16812499,  0.68515917, -0.29914157]]),
 array([[-1., -1.,  1., -1.]]))

#### 30. How to find common values between two arrays? (★☆☆)

(**hint**: np.intersect1d)


In [79]:
a, b = np.array([1, 2, 3]), np.array([3, 4, 5])
np.intersect1d(a, b)


array([3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

(**hint**: np.seterr, np.errstate)


In [80]:
"np.seterr(all='ignore')"


"np.seterr(all='ignore')"

#### 32. Is the following expressions true? (★☆☆)

(**hint**: imaginary number)


```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


In [81]:
False


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

(**hint**: np.datetime64, np.timedelta64)


In [82]:
today = np.datetime64('today')
today-np.timedelta64(1), today, today+np.timedelta64(1)


(numpy.datetime64('2022-02-07'),
 numpy.datetime64('2022-02-08'),
 numpy.datetime64('2022-02-09'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

(**hint**: np.arange(dtype=datetime64\['D'\]))


In [83]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))


In [84]:
A = np.random.randint(1, 5, 3).astype('float32')
print("before: ", A)
B = np.random.randint(1, 5, 3).astype('float32')
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print("after: ", A)


before:  [1. 1. 4.]
after:  [ -2.5  -2.5 -14. ]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

(**hint**: %, np.floor, np.ceil, astype, np.trunc)


In [85]:
x = np.random.randn(1, 5)
print(x - x % 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))


[[-1.  0.  0.  0. -1.]]
[[-1.  0.  0.  0. -1.]]
[[0 0 0 0 0]]
[[-0.  0.  0.  0. -0.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

(**hint**: np.arange)


In [86]:
np.tile(np.arange(5), (5, 1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

(**hint**: np.fromiter)


In [87]:
np.fromiter(range(5), dtype='int16')


array([0, 1, 2, 3, 4], dtype=int16)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

(**hint**: np.linspace)


In [88]:
np.linspace(0, 1, 12)[1:-1]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

(**hint**: sort)


In [89]:
x = np.random.randint(1, 10, 10)
x.sort()
x


array([2, 3, 3, 3, 5, 5, 6, 8, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

(**hint**: np.add.reduce)


In [90]:
np.add.reduce([1, 2, 3])


6

#### 42. Consider two random array A and B, check if they are equal (★★☆)

(**hint**: np.allclose, np.array_equal)


In [91]:
a, b = [[2.0], [3]], [[2.00001], [3]]
np.allclose(a, b), np.array_equal(a, b)


(True, False)

#### 43. Make an array immutable (read-only) (★★☆)

(**hint**: flags.writeable)


In [92]:
x = np.array([1, 2, 3])
x.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

(**hint**: np.sqrt, np.arctan2)


In [93]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
R, T


(array([0.64874685, 0.59357487, 0.54205484, 0.83543182, 0.82913026,
        1.02675154, 0.50580704, 0.37678673, 0.82531922, 1.05455746]),
 array([0.04228774, 0.7150018 , 0.60238569, 0.98769171, 1.17385967,
        0.52417818, 0.29389739, 0.56201049, 0.95868705, 1.2083219 ]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

(**hint**: argmax)


In [94]:
x = np.random.randint(1, 10, 10)
print(x)
x[x.argmax()] = 0
x


[8 5 9 1 3 2 8 1 1 2]


array([8, 5, 0, 1, 3, 2, 8, 1, 1, 2])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

(**hint**: np.meshgrid)


In [95]:
x, y = np.random.randint(1, 10, 10).reshape((2, 5))
X, Y = np.meshgrid(x, y)
X, Y


(array([[5, 1, 3, 4, 9],
        [5, 1, 3, 4, 9],
        [5, 1, 3, 4, 9],
        [5, 1, 3, 4, 9],
        [5, 1, 3, 4, 9]]),
 array([[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [6, 6, 6, 6, 6]]))

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

(**hint**: np.subtract.outer)


In [96]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
C


array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

(**hint**: np.iinfo, np.finfo, eps)


In [97]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

(**hint**: np.set_printoptions)


In [98]:
np.set_printoptions(threshold=float("inf"))
Z = np.ones((10, 10))
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

(**hint**: argmin)


In [99]:
a = np.arange(100)
b = np.random.randint(0, 100, 100)
a[(np.abs(a-b)).argmin()]


39

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

(**hint**: dtype)


In [100]:
DTYPE = np.dtype([('position', [('x', float, 1),
                                ('y', float, 1)], 1),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)], 1)])
np.zeros((1, 1), dtype=DTYPE)


/tmp/ipykernel_3280/2643626663.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  DTYPE = np.dtype([('position', [('x', float, 1),


array([[((0., 0.), (0., 0., 0.))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

(**hint**: np.atleast_2d, T, np.sqrt)


In [101]:
x, y = np.random.randint(1, 10, (100, 2)).T
x, y = map(np.atleast_2d, [x, y])
dx, dy = (x - x.T), (y - y.T)
distances = np.sqrt(dx**2+dy**2)
distances


array([[ 0.        ,  5.        ,  5.09901951,  2.82842712,  4.47213595,
         4.        ,  1.41421356,  3.        ,  2.        ,  3.16227766,
         2.23606798,  3.60555128,  4.12310563,  5.09901951,  2.23606798,
         6.08276253,  1.        ,  2.        ,  1.41421356,  3.60555128,
         5.65685425,  5.38516481,  6.08276253,  4.47213595,  4.        ,
         6.40312424,  6.08276253,  1.41421356,  2.82842712,  4.47213595,
         2.23606798,  3.16227766,  4.12310563,  5.        ,  6.08276253,
         1.        ,  4.12310563,  5.83095189,  6.        ,  0.        ,
         3.        ,  4.        ,  2.23606798,  4.47213595,  6.08276253,
         3.16227766,  5.38516481,  0.        ,  6.70820393,  6.40312424,
         4.24264069,  1.        ,  4.47213595,  4.24264069,  1.41421356,
         3.16227766,  4.12310563,  2.        ,  4.12310563,  6.40312424,
         4.        ,  1.        ,  4.12310563,  1.        ,  2.23606798,
         6.70820393,  3.16227766,  5.83095189,  7.2

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

(**hint**: astype(copy=False))


In [102]:
x = np.float32(2)
x = x.astype(np.int32)
type(x)


numpy.int32

#### 54. How to read the following file? (★★☆)

(**hint**: np.genfromtxt)


```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


In [103]:
from io import StringIO
file = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')

np.genfromtxt(file, delimiter=",")


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

(**hint**: np.ndenumerate, np.ndindex)


In [104]:

x = np.array([1, 2, 3])
for i, x_ in np.ndenumerate(x):
    print(i, x_)
for i in np.ndindex(x.shape):
    print(i, x[i])
# np.ndindex?


(0,) 1
(1,) 2
(2,) 3
(0,) 1
(1,) 2
(2,) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

(**hint**: np.meshgrid, np.exp)


In [105]:
X, Y = np.meshgrid(np.arange(2), np.arange(2))
D = np.sqrt(X**2+Y**2)
# print(D)
sigma, mu = 1.0, 0.0
np.exp(-((D-mu)**2 / (2.0 * sigma**2)))


array([[1.        , 0.60653066],
       [0.60653066, 0.36787944]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

(**hint**: np.put, np.random.choice)


In [106]:
x = np.arange(25).reshape((5, 5))
i = np.random.choice(25, 13)
np.put(x, i, np.ones(13)*-1)
x


array([[-1,  1, -1,  3,  4],
       [ 5, -1,  7,  8, -1],
       [10, -1, -1, 13, 14],
       [-1, -1, 17, 18, 19],
       [20, -1, -1, 23, -1]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

(**hint**: mean(axis=,keepdims=))


In [107]:
x = np.arange(25).reshape((5, 5))
x - np.mean(x, axis=1, keepdims=True)


array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### 59. How to sort an array by the nth column? (★★☆)

(**hint**: argsort)


In [108]:
x = np.random.randint(1, 10, 25).reshape((5, 5))
x, x[np.argsort(x[:, 0])]


(array([[4, 4, 8, 6, 9],
        [6, 9, 2, 8, 6],
        [7, 8, 9, 8, 6],
        [4, 1, 4, 7, 7],
        [5, 7, 6, 8, 6]]),
 array([[4, 4, 8, 6, 9],
        [4, 1, 4, 7, 7],
        [5, 7, 6, 8, 6],
        [6, 9, 2, 8, 6],
        [7, 8, 9, 8, 6]]))

#### 60. How to tell if a given 2D array has null columns? (★★☆)

(**hint**: any, ~)


In [109]:
x = np.array([[1, 3, 2, 0], [1, 1, 1, 1]])
np.all(x, axis=0,)


array([ True,  True,  True, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

(**hint**: np.abs, argmin, flat)


In [110]:
x = np.random.randint(-10, 10, 10)
x[np.abs(x-3).argmin()]


2

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

(**hint**: np.nditer)


In [111]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands)


(array([[0],
       [1],
       [2]]), array([[0, 1, 2]]), array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]]))


#### 63. Create an array class that has a name attribute (★★☆)

(**hint**: class method)


In [112]:
class Foo:
    def __init__(self, name):
        self.name = name


x = Foo('spam')
x.name


'spam'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

(**hint**: np.bincount | np.add.at)


In [113]:
x = np.array([1, 1, 2, 3, 5])
np.add.at(x, np.array([0, 1, 1]), 1)
x


array([2, 3, 2, 3, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

(**hint**: np.bincount)


In [114]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.array(np.bincount(I, X), dtype=int)
F


array([0, 7, 0, 6, 5, 0, 0, 0, 0, 3])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

(**hint**: np.unique)


In [115]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
colors.shape[0]


64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

(**hint**: sum(axis=(-2,-1)))


In [116]:
np.ones((2, 2, 2, 2)).sum(axis=(-2, -1))


array([[4., 4.],
       [4., 4.]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

(**hint**: np.bincount)


In [117]:
D = np.random.uniform(0, 1, 100)  # 1-D vector
S = np.random.randint(0, 10, 100)  # Index groups
D_sums = np.bincount(S, weights=D)  # sum of vaules grouped by index
D_counts = np.bincount(S)  # count of each index group
D_sums / D_counts  # mean  = sum/count


array([0.52439191, 0.53573433, 0.56625185, 0.44058741, 0.41975962,
       0.50109645, 0.4887542 , 0.56633479, 0.47823942, 0.4836965 ])

#### 69. How to get the diagonal of a dot product? (★★★)

(**hint**: np.diag)


In [118]:
np.diag(np.dot(np.ones((3, 3)), np.ones((3, 3))))


array([3., 3., 3.])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

(**hint**: array\[::4\])


In [119]:
x = np.array([1, 2, 3, 4, 5])
z = np.zeros(x.size*(3+1)-3)
z[::4] = x
z


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

(**hint**: array\[:, :, None\])


In [120]:
A = np.ones((5, 5, 3))
B = 2*np.ones((5, 5))
A * B[:, :, None]
x = np.array([1, 2, 3])


#### 72. How to swap two rows of an array? (★★★)

(**hint**: array\[\[\]\] = array\[\[\]\])


In [121]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

(**hint**: repeat, np.roll, np.sort, view, np.unique)


In [122]:
vertices = np.random.randint(0, 10, (10, 3))
sides = np.roll(vertices.repeat(2, axis=1), -1, axis=1)
sides = sides.reshape(-1, 2)
sides = np.sort(sides, axis=1)
sides_tuple = sides.view(dtype=[('xy1', sides.dtype), ('xy2', sides.dtype)])
np.unique(sides_tuple).size


24

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

(**hint**: np.repeat)


In [123]:
bin_cnt = np.array([0, 2, 3, 1, 0])
np.repeat(np.arange(bin_cnt.size), bin_cnt)


array([1, 1, 2, 2, 2, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

(**hint**: np.cumsum)


In [124]:
x = np.array([1, 2, 3, 4, 5])
sliding_window_view(x, window_shape=3).mean(axis=-1)


array([2., 3., 4.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

(**hint**: from numpy.lib import stride_tricks)


In [125]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(10)
sliding_window_view(Z, window_shape=3)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

(**hint**: np.logical_not, np.negative)


In [126]:
x = np.array([True])
np.logical_not(x, out=x)
x


array([False])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0\[i\],P1\[i\])? (★★★)


In [127]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0]-p[..., 0])*T[:, 0] + (P0[:, 1]-p[..., 1])*T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
distance(P0, P1, p)


array([ 5.10078164, 16.55453029,  9.0999602 , 12.07636666,  1.38554206,
        3.21875085, 11.08631417, 11.03343168,  5.38214075,  1.32064589])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)


In [128]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
np.array([distance(P0, P1, p_i) for p_i in p])


array([[12.57014938, 10.21953836,  0.51928617,  8.55959522,  3.05082848,
         0.7468517 ,  2.72772785,  4.90467197, 13.11689354,  1.04667201],
       [11.78151293,  7.91055869,  1.72206339,  8.48632035,  4.65450068,
         1.25148767,  4.24533736,  5.02505767, 12.86602095,  1.25501568],
       [ 0.78188635,  0.74272831,  7.1705106 ,  0.58072449,  3.78982839,
         3.64165429,  2.78681892,  3.36999352,  3.23701769,  8.12466827],
       [ 2.27334792,  1.88294553, 10.14083734,  1.80468703,  7.24530179,
         6.97907773,  6.23566122,  0.78413475,  5.42344328, 10.8190037 ],
       [ 4.63460436, 16.26778731,  8.15574367,  1.58678989,  7.98358155,
        10.4412797 ,  8.46331339,  5.66618347,  3.4232759 ,  7.39807901],
       [ 3.5321878 , 15.61628802,  7.67863952,  2.51700829,  8.132303  ,
        10.26980127,  8.6699317 ,  6.53447308,  2.44185224,  6.77698886],
       [ 2.43027242,  6.9906196 ,  1.01990698,  0.88440428,  0.88135867,
         1.98221232,  1.67004074,  4.19368055

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

(**hint**: minimum, maximum)


In [129]:
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[3 3 8 7 7 9 8 6 9 2]
 [3 7 5 1 1 9 1 0 1 4]
 [7 2 6 1 4 3 8 1 6 6]
 [0 7 8 4 9 3 3 8 1 6]
 [1 9 8 8 4 4 9 0 3 0]
 [9 7 0 0 6 6 9 2 9 2]
 [0 5 1 6 2 0 7 2 3 8]
 [5 1 2 7 0 4 5 9 1 6]
 [1 5 9 9 4 3 2 0 6 4]
 [2 4 3 5 5 8 7 4 6 7]]
[[0 0 0 0 0]
 [0 3 3 8 7]
 [0 3 7 5 1]
 [0 7 2 6 1]
 [0 0 7 8 4]]


/tmp/ipykernel_3280/3650382191.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

(**hint**: stride_tricks.as_strided)


In [130]:
Z = np.arange(1, 15, dtype=np.uint32)
sliding_window_view(Z, window_shape=4)


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)


In [131]:
Z = np.random.uniform(0, 1, (10, 10))
np.linalg.matrix_rank(Z)


10

#### 83. How to find the most frequent value in an array?

(**hint**: np.bincount, argmax)


In [132]:
Z = np.random.randint(0, 10, 50)
np.bincount(Z).argmax()


4

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

(**hint**: stride_tricks.as_strided)


In [133]:
Z = np.random.randint(0, 5, (10, 10))
sliding_window_view(Z, window_shape=(3, 3))


array([[[[0, 3, 3],
         [4, 1, 2],
         [2, 1, 1]],

        [[3, 3, 0],
         [1, 2, 1],
         [1, 1, 2]],

        [[3, 0, 4],
         [2, 1, 4],
         [1, 2, 2]],

        [[0, 4, 3],
         [1, 4, 4],
         [2, 2, 4]],

        [[4, 3, 4],
         [4, 4, 3],
         [2, 4, 3]],

        [[3, 4, 1],
         [4, 3, 2],
         [4, 3, 2]],

        [[4, 1, 3],
         [3, 2, 0],
         [3, 2, 3]],

        [[1, 3, 4],
         [2, 0, 1],
         [2, 3, 2]]],


       [[[4, 1, 2],
         [2, 1, 1],
         [0, 2, 1]],

        [[1, 2, 1],
         [1, 1, 2],
         [2, 1, 1]],

        [[2, 1, 4],
         [1, 2, 2],
         [1, 1, 1]],

        [[1, 4, 4],
         [2, 2, 4],
         [1, 1, 4]],

        [[4, 4, 3],
         [2, 4, 3],
         [1, 4, 0]],

        [[4, 3, 2],
         [4, 3, 2],
         [4, 0, 1]],

        [[3, 2, 0],
         [3, 2, 3],
         [0, 1, 2]],

        [[2, 0, 1],
         [2, 3, 2],
         [1, 2, 3]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

(**hint**: class method)


In [134]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)


S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
S


Symetric([[ 6,  8,  8,  8,  8],
          [ 8,  2,  6, 16,  9],
          [ 8,  6,  0, 42, 16],
          [ 8, 16, 42,  2,  8],
          [ 8,  9, 16,  8,  2]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

(**hint**: np.tensordot)


In [135]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

(**hint**: np.add.reduceat)


In [136]:
Z = np.ones((16, 16))
k = 4

windows = sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
S


array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [137]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] +
         Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    Z = iterate(Z)
Z


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

#### 89. How to get the n largest values of an array (★★★)

(**hint**: np.argsort | np.argpartition)


In [138]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

Z[np.argsort(Z)[-n:]]


array([9995, 9996, 9997, 9998, 9999])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

(**hint**: np.indices)


In [139]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


cartesian(([1, 2, 3], [4, 5], [6, 7]))


array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

(**hint**: np.core.records.fromarrays)


In [140]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
R


rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

(**hint**: np.power, \*, np.einsum)


In [141]:
x = np.random.rand(int(5e7))

np.power(x, 3)
x*x*x
np.einsum('i,i,i->i', x, x, x)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

(**hint**: np.where)


In [ ]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
rows


array([1, 5, 6])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)


In [ ]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1), :]
U


[[3 2 1]
 [4 1 3]
 [3 3 3]
 [2 2 2]
 [2 2 0]
 [0 2 4]
 [0 1 2]
 [3 3 4]
 [2 4 0]
 [0 4 2]]
[[3 2 1]
 [4 1 3]
 [2 2 0]
 [0 2 4]
 [0 1 2]
 [3 3 4]
 [2 4 0]
 [0 4 2]]


array([[3, 2, 1],
       [4, 1, 3],
       [2, 2, 0],
       [0, 2, 4],
       [0, 1, 2],
       [3, 3, 4],
       [2, 4, 0],
       [0, 4, 2]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

(**hint**: np.unpackbits)


In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
B[:, ::-1]


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

(**hint**: np.ascontiguousarray)


In [ ]:
Z = np.random.randint(0, 2, (6, 3))
T = np.ascontiguousarray(Z).view(
    np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
uZ


array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

(**hint**: np.einsum)


In [ ]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[2.58655829e-01, 8.29660194e-03, 3.15147828e-01, 1.98396532e-01,
        9.91403534e-02, 1.56199760e-01, 1.10765975e-01, 7.91421838e-02,
        2.93850653e-01, 3.67918921e-01],
       [1.13817236e-02, 3.65078298e-04, 1.38675609e-02, 8.73011250e-03,
        4.36250790e-03, 6.87331310e-03, 4.87407422e-03, 3.48252140e-03,
        1.29304138e-02, 1.61896659e-02],
       [3.57124918e-01, 1.14550803e-02, 4.35123162e-01, 2.73925183e-01,
        1.36882632e-01, 2.15664294e-01, 1.52934074e-01, 1.09271251e-01,
        4.05718250e-01, 5.07983969e-01],
       [1.76313497e-01, 5.65540282e-03, 2.14821433e-01, 1.35237572e-01,
        6.75793100e-02, 1.06474021e-01, 7.55039487e-02, 5.39474996e-02,
        2.00304151e-01, 2.50793002e-01],
       [3.38249410e-01, 1.08496326e-02, 4.12125129e-01, 2.59447120e-01,
        1.29647827e-01, 2.04265557e-01, 1.44850885e-01, 1.03495820e-01,
        3.84274387e-01, 4.81134945e-01],
       [5.80381972e-02, 1.86162370e-03, 7.07140909e-02, 4.45169827e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

(**hint**: np.cumsum, np.interp)


In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200)  # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

(**hint**: np.logical_and.reduce, np.mod)


In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
X[M]


array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

(**hint**: np.percentile)


In [ ]:
X = np.random.randn(100)  # random 1D array
N = 1000  # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint


array([-0.29605434,  0.12171489])